name: Makefile CI

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OBJ_DIR: /tmp/obj

    steps:
    - uses: actions/checkout@v2

    - name: Get compiler version
      run:  echo "COMPILER_VERSION=$(make compiler-version)" >> $GITHUB_ENV

    - name: Cache objects
      uses: actions/cache@v2
      with:
        path: ${{ env.OBJ_DIR }}
        key: ${{ runner.os }}-${{ runner.arch }}-${{ env.COMPILER_VERSION }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}

    - name: Print env
      run: make info

    - name: Print runner
      run: |
        echo ${{ runner.name }}
        echo ${{ env.COMPILER_VERSION }}

    - name: Build program
      run: |
        make release -j2  2>&1 |  awk '{ r = gensub(/(.*):([0-9]{1,}):([0-9]{1,}): (error|warning): (.*) \[(.*)\]/, "::\\4 file=\\1,line=\\2,col=\\3,title=\\6::\\5\n\\0", "g"); print r;}' && (exit ${PIPESTATUS[0]})
