name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print env
      run: make info

    - name: Build program
      run: |
        make release -j2  2>&1 |  awk '{ r = gensub(/(.*):([0-9]{1,}):([0-9]{1,}): (error|warning): (.*) \[(.*)\]/, "::\\4 file=\\1,line=\\2,col=\\3,title=\\6::\\5\n\\0", "g"); print r;}' && (exit ${PIPESTATUS[0]})
