name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print env
      run: make info
      env:
        CXXFLAGS: -Werror

    - name: Build program
      run: make release
      env:
        CXXFLAGS: -Werror
